<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clerk Tasks (181)</name>
   <tag></tag>
   <elementGuidId>8ab06ca7-2e99-4e3c-a5ca-28b168f1472c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-menu-nav']/div/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>15b0e73c-9d3a-4d2d-baff-5516082e32b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/task</value>
      <webElementGuid>f6aad99c-2824-49db-9500-a01a139f3e7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-nav nav-item  dropdown-item</value>
      <webElementGuid>b2a74586-88fe-4965-83d0-9a373deed0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clerk Tasks (181)</value>
      <webElementGuid>42fe002f-78bc-43a4-9c31-d091f39e98bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu-nav&quot;)/div[@class=&quot;main-nav nav-item taskDropdown active-tab-dropdown nav-item show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;main-nav nav-item  dropdown-item&quot;]</value>
      <webElementGuid>b61f23a3-ced0-4ada-8f37-a6d2fb2ed5f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu-nav']/div/div/a[3]</value>
      <webElementGuid>3094b5c4-a1e8-4bc3-b330-e8f226f1e623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All tasks (749)'])[1]/following::a[1]</value>
      <webElementGuid>4aab6851-4adc-4866-8f5d-bfb0bff1a615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clerk Unassigned Tasks (88)'])[1]/following::a[2]</value>
      <webElementGuid>641ac30e-8991-4080-ac14-5aca1046906c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviewer Tasks (484)'])[1]/preceding::a[1]</value>
      <webElementGuid>da79da64-cccc-40e1-aabf-7965735e102c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My task (254)'])[1]/preceding::a[2]</value>
      <webElementGuid>e282152c-28b9-469b-820f-07b76db4207a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clerk Tasks']/parent::*</value>
      <webElementGuid>178a01a6-66d3-4856-a8f4-391ff968ac56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/task')])[3]</value>
      <webElementGuid>376b12bd-429f-4f86-9173-54bc0b79d3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a[3]</value>
      <webElementGuid>f21c73bf-3d20-4c6b-91a6-9f0535a1c3ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/task' and (text() = 'Clerk Tasks (181)' or . = 'Clerk Tasks (181)')]</value>
      <webElementGuid>14029547-9646-49de-8393-85042267e202</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
