<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ApproveReject ApplicationsTwo Step Appr_717e79</name>
   <tag></tag>
   <elementGuidId>d08a3d4f-de54-40aa-81d2-da569a4c58bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/section/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.clickable.shadow.border.false</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b349e5e4-f343-4828-8fde-27983a3968ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>clickable shadow border  false</value>
      <webElementGuid>b4c18439-44f8-4fbe-80d9-eda921d6b7b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve/Reject ApplicationsTwo Step Approval-listener      Created a few seconds ago50StatusReviewed</value>
      <webElementGuid>253261a5-76b9-4ce5-9aaa-34fc8f1ed5e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;p-2 row&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-md-4 col-sm-12 col-12&quot;]/section[1]/div[@class=&quot;service-task-list list-group&quot;]/div[@class=&quot;clickable shadow border  false&quot;]</value>
      <webElementGuid>41e4ef62-1942-4422-8165-324b120e46f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/section/div/div[2]</value>
      <webElementGuid>e1b73d9a-d3bf-437f-8505-416903c21fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Created'])[1]/following::div[6]</value>
      <webElementGuid>07034e7b-baca-4214-a4e7-b8b29ddbca80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NRS Reviewer Task (0)'])[1]/following::div[19]</value>
      <webElementGuid>67bcd7f0-d9e0-4c0d-9ee5-4241495fa16d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div[2]</value>
      <webElementGuid>50cc6254-0ee9-4f43-8751-aba2aa8a1fc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Approve/Reject ApplicationsTwo Step Approval-listener      Created a few seconds ago50StatusReviewed' or . = 'Approve/Reject ApplicationsTwo Step Approval-listener      Created a few seconds ago50StatusReviewed')]</value>
      <webElementGuid>f875ef46-d7f6-4647-99e5-b265eabf3544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
