<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_search_form name</name>
   <tag></tag>
   <elementGuidId>69f07b06-deb8-46a7-9aad-0cdae90328e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;text-filter-column-title&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#text-filter-column-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aae4b5ff-e06d-4b72-b648-6705f617c604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>delay</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>7939650b-ce81-4b8b-93fd-bfe135007adc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cd95b8dd-bfcf-40d4-b221-53a2828ecd21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>text-filter-column-title</value>
      <webElementGuid>df212cc4-ca8b-447d-ae89-c36d7d1535dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filter text-filter form-control icon-search</value>
      <webElementGuid>be73042c-60b4-4798-bfbe-fcf12a50a601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search by form name</value>
      <webElementGuid>2d50c89d-139a-439a-b036-366888e4ce3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;text-filter-column-title&quot;)</value>
      <webElementGuid>4ba1924a-9d96-4fe1-833e-9771588b96a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='text-filter-column-title']</value>
      <webElementGuid>1afa751f-3128-4e5b-8bef-81b1449e57f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/section/div/div/div/div/table/tbody/tr/th/label/input</value>
      <webElementGuid>e52bcbd0-7352-41d6-ac1d-8a4823fc0b9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>459313c2-6f2c-4d7d-a742-93ee78f0e53d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'text-filter-column-title' and @placeholder = 'Search by form name']</value>
      <webElementGuid>979f780a-7de9-4152-9e06-032566d99f7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
