<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_(Form Name)</name>
   <tag></tag>
   <elementGuidId>e78bd01c-2ca4-4845-81e3-c39e5d253322</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main']/div/div/section/div/div/div/div[2]/div/div[2]/span[2]/div/div/div[9]/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e9f6db6b-c9da-469b-9da3-3776f4446823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-muted</value>
      <webElementGuid>7bd1f917-f06a-4fb1-80d0-1a619f1be6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> (Form Name)</value>
      <webElementGuid>bfa0d328-7dc0-4cd5-86c7-adfde1c567c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)/div[@class=&quot;p-2 row&quot;]/div[@class=&quot;col-xl-3 col-lg-3 col-md-4 col-sm-12 col-12&quot;]/section[1]/div[@class=&quot;service-task-list list-group&quot;]/div[@class=&quot;filter-container&quot;]/div[1]/div[2]/div[@class=&quot;filter-details&quot;]/div[@class=&quot;box-container&quot;]/span[2]/div[1]/div[@class=&quot;filter-items variable-filter-item&quot;]/div[@class=&quot;clickable p-0 mb-2 text-truncate&quot;]/span[1]/span[@class=&quot;text-muted&quot;]</value>
      <webElementGuid>4c1b1d57-3bf2-4842-9fdb-84246f6a0a84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main']/div/div/section/div/div/div/div[2]/div/div[2]/span[2]/div/div/div[9]/span/span</value>
      <webElementGuid>29e94359-8c28-4f74-9a81-28fffec2cf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/span/span</value>
      <webElementGuid>22b4b8ad-362e-4e2b-a2d5-cf9780630796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' (Form Name)' or . = ' (Form Name)')]</value>
      <webElementGuid>ac4dba00-6f5d-4c99-ba81-4df90ff876e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
