<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Name_filters</name>
   <tag></tag>
   <elementGuidId>83c4671d-ec7d-4423-818b-52495ce161ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.filters</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;task-search-input&quot;]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>afde49d0-5b32-4c7f-9e69-27d174d9296f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>147928d0-d860-4d93-94a6-f03a4b9ebc4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>filters</value>
      <webElementGuid>f420130c-ecb6-4abf-a362-5ccb60870214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search-input&quot;)/input[@class=&quot;filters&quot;]</value>
      <webElementGuid>cb3e7a67-5c40-49dc-872b-de97a4f763a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
      <webElementGuid>1acac6e7-9a51-4891-b13c-9b7ea305e135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='task-search-input']/input</value>
      <webElementGuid>4115cc12-3a0d-41d5-ab3f-0e5f183b462c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5d7fd543-87a4-47db-8854-7d63f3229b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text']</value>
      <webElementGuid>8e561294-3fbb-451d-8a4a-dd3864f8c800</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
