<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Clerk Tasks (180)</name>
   <tag></tag>
   <elementGuidId>777a45e0-682f-41fb-89a8-6aa335765b80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='main-menu-nav']/div/div/a[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7cc9689e-16bf-4741-9739-2a0bfc693f1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/task</value>
      <webElementGuid>6843ed04-44fa-430b-ba3f-ba21733de80b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>main-nav nav-item  dropdown-item</value>
      <webElementGuid>ed936c7e-808e-4884-a71c-161c50ed01e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Clerk Tasks (180)</value>
      <webElementGuid>71cdf6a2-3fe0-4a8a-922d-8b51b08f596d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-menu-nav&quot;)/div[@class=&quot;main-nav nav-item taskDropdown active-tab-dropdown nav-item show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[@class=&quot;main-nav nav-item  dropdown-item&quot;]</value>
      <webElementGuid>05b5be4a-76e7-4ffa-b15e-574668695759</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='main-menu-nav']/div/div/a[3]</value>
      <webElementGuid>5204e1db-ddab-42c4-a793-71549de06e2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All tasks (748)'])[1]/following::a[1]</value>
      <webElementGuid>188ff32c-287f-4ea8-a15c-dc04c0f11f76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clerk Unassigned Tasks (87)'])[1]/following::a[2]</value>
      <webElementGuid>29fd51b6-df65-405e-a464-d707d5481030</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviewer Tasks (484)'])[1]/preceding::a[1]</value>
      <webElementGuid>915d8a6e-a046-4768-be4a-91f058cdf5f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My task (254)'])[1]/preceding::a[2]</value>
      <webElementGuid>7cc9d027-e082-49ed-8787-75fbaab4d5b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Clerk Tasks']/parent::*</value>
      <webElementGuid>3b6f7868-625e-4ba0-8bf2-b767ff3c07a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/task')])[3]</value>
      <webElementGuid>5289b359-c5b3-44cd-a16f-055a949223a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/a[3]</value>
      <webElementGuid>47228709-4943-43bf-98e5-6c317680c866</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/task' and (text() = 'Clerk Tasks (180)' or . = 'Clerk Tasks (180)')]</value>
      <webElementGuid>4cfc916f-0de2-48c4-a0cb-2380ce30fd03</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
