<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__1</name>
   <tag></tag>
   <elementGuidId>28b98085-31a4-4ae7-b20d-f79cecee73fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='task-search-input']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#task-search-input > span.click-element</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>46ba5f88-bc53-4309-9f35-fdd328f2bc2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>3fe901cf-ec2d-4271-9617-084a54b4572a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-element</value>
      <webElementGuid>d61a3e1b-9539-44ba-abfc-5b7020aa947b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>??</value>
      <webElementGuid>f67f6130-2371-4380-b2b3-223fde3616d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search-input&quot;)/span[@class=&quot;click-element&quot;]</value>
      <webElementGuid>8a8cee7a-760f-4322-8e39-b1f3525e396c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='task-search-input']/span</value>
      <webElementGuid>d14df0c6-f7c9-492d-b836-277710f3dd55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='applicationStatus'])[1]/following::span[4]</value>
      <webElementGuid>d2d8321b-fc2c-4ca6-a6ec-1d148490fd64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Process Variables :'])[1]/following::span[7]</value>
      <webElementGuid>f40dd082-2e15-40d5-ac74-773c673ccf86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='For Variable, ignore case ofNamevalue'])[1]/preceding::span[2]</value>
      <webElementGuid>4f65ebd3-5bc8-4cce-b17e-cb9be6418b93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Applications'])[1]/preceding::span[9]</value>
      <webElementGuid>c3a06960-dd82-46b3-a389-be5d6455e114</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='??']/parent::*</value>
      <webElementGuid>76701c56-0e0b-4c0f-9098-7757a6d200b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span[2]/span</value>
      <webElementGuid>3890e485-783a-4e4a-84fe-46d781820e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'value' and (text() = '??' or . = '??')]</value>
      <webElementGuid>dc21edc1-dcf7-476f-8768-207891cd9d6c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
