<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CreatedAll of the criteria are met.Assi_2abde1</name>
   <tag></tag>
   <elementGuidId>3a478da6-ef1d-48d9-8ed5-40464ce631e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.container-fluid.content.main-container</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>dff8b0cf-1671-45f7-aa2c-682fcbe86ae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>container-fluid content main-container</value>
      <webElementGuid>c4a47dff-62dc-4722-94ba-98a2b3a5e4cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CreatedAll of the criteria are met.Assignee =likeNo task matching filters found.Select a task in the list.Powered by formsflow.ai v5.0.0 </value>
      <webElementGuid>8c9ba768-b129-411c-b371-5d77c75530d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[1]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;container-fluid content main-container&quot;]</value>
      <webElementGuid>62f977a7-58ba-4537-9d70-9ad8485872cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div</value>
      <webElementGuid>d8cadc38-fc6e-4a9f-a687-dcc364e8f88f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Processes'])[1]/following::div[8]</value>
      <webElementGuid>c1b88b70-78c1-4bd1-bed7-bc38e97ec501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div</value>
      <webElementGuid>648f7453-053c-44a9-bc3b-23acc2f4960d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'CreatedAll of the criteria are met.Assignee =likeNo task matching filters found.Select a task in the list.Powered by formsflow.ai v5.0.0 ' or . = 'CreatedAll of the criteria are met.Assignee =likeNo task matching filters found.Select a task in the list.Powered by formsflow.ai v5.0.0 ')]</value>
      <webElementGuid>bfe1df71-a32c-4f6c-a4aa-6c6f96e4f7b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
