<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Invalid Date</name>
   <tag></tag>
   <elementGuidId>71a29f65-cef3-4410-98d8-d14abd5ab90d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#task-search-input > span.click-element</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='task-search-input']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a5f247cf-2dab-49a9-8cd1-280ad1608dee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>2bd91c44-4cab-4aac-b2b6-718b78ebf54a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>click-element</value>
      <webElementGuid>4ab273c6-8c4d-4ddf-820d-03ddbd4ab0db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Invalid Date</value>
      <webElementGuid>19c77e3c-8e29-49b2-a09f-8f161b1a538f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;task-search-input&quot;)/span[@class=&quot;click-element&quot;]</value>
      <webElementGuid>d4ef4398-f1b3-4fa9-bdb6-7557334791cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='task-search-input']/span</value>
      <webElementGuid>29031e89-843e-48c3-a3ee-7976b4cb40cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Due Date'])[1]/following::span[6]</value>
      <webElementGuid>75267389-54bb-4ea0-99d8-8d3cc94ba513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No task matching filters found.'])[1]/preceding::span[2]</value>
      <webElementGuid>bcf776a4-6aa6-4a2d-81f6-bb241f19389b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select a task in the list.'])[1]/preceding::span[2]</value>
      <webElementGuid>34ca135a-6aeb-44dd-aabd-682925eba097</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Invalid Date']/parent::*</value>
      <webElementGuid>b43e743d-4839-42f4-aeb2-b843c75b9ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span[2]/div/span[2]/span</value>
      <webElementGuid>ef03d974-6c9b-4144-8efd-cbd97715e41b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@title = 'value' and (text() = 'Invalid Date' or . = 'Invalid Date')]</value>
      <webElementGuid>3fed3ac1-0297-4ac5-a830-766fe7925c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
